### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by JarrodOlivier** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#11] opened 2021-03-09 10:42 UTC
_Device compatibility issue_

https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image

Running the app on a Samsung device using Android 7 (Galaxy S6) . (As seen [here](https://stackoverflow.com/a/43651170/7117011)).

An image with a height greater than 1024px crashes the app when launching on the device, app cannot run until the image is removed from the component tree or resized.

**Steps to reproduce?**
1. Using the device mentioned above and the default "androidparty" image in the codelab.
2. Complete "Adopt good coding practices"
3. Run on device
4. Error received: java.lang.RuntimeException: Canvas: trying to draw too large(160698048bytes) bitmap

**Versions**
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true

**Comment by JarrodOlivier** [comment] 2021-03-09 10:46
Duplicate of #9

**Comment by ashnohe** [comment] 2021-11-05 19:25
Closing as duplicate of #9

**Closed by ashnohe** 2021-11-05 19:25 UTC
