### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by thoomaas** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#21] opened 2021-07-12 19:52 UTC
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#3

The step about "extract ressource" is not doable in Android studio 4.2.2

The extract ressource does not show anymore, and axtract ressource command is not available with a CTRL+Shift+A call

thank you

**Comment by ashnohe** [comment] 2021-11-05 19:55
Duplicate of #15

**Closed by ashnohe** 2021-11-05 19:55 UTC
