### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by AndroidDude123** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#18] opened 2021-06-20 19:38 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#4

**In which task and step of the codelab can this issue be found?**
If I were to follow the description exactly I would be loading a code that does not run. 

**Describe the problem**
I am new to android studios but I am fairly competent in software. I follow the description exactly but I loaded a file that does not have main_activity.xml and MainActivity.xml layouts. I cannot run the code as described on the webpage. I feel like I'm running a dead code. It's really confusing and kept me stuck for a good half hour.

**Steps to reproduce?**
1. Newly install Android Studio following previous lessions
2. Download android-basics-kotlin-birthday-card(bla-bla).zip
3. unzip onto desktop
4. Import file as instructed

**Versions**
_Android Studio version:_ 4.2.1
_API version of the emulator:_ notsure 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-05 19:47
Duplicate of #10 

@AndroidDude123 thank you for raising this issue. Opening "Happy Birthday" instead of "android-basics-kotlin-birthday-card-with-image-app-solution-master" will resolve this issue.

**Closed by ashnohe** 2021-11-05 19:47 UTC
