### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by willacuna** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#19] opened 2021-06-25 17:12 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#3

Step 4: Adopt good coding practices, Part: Translating

**Describe the problem**
When clicking on the orange triangle under the component tree the attributes come up.  Cannot pull up the suggest fix ==> no fix button.

SOLUTION**:
A list of all warnings for the component tree's components is to the left of attributes.  Click there, on that yellow triangle, which will bring up (for this particular step) your 3 warning messages.  From here, you can see the messages and scroll down to click fix.

**Versions**
_Android Studio version:_  4.2.1
_API version of the emulator:_  30, Android 11.0 (R)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by david22020** [comment] 2021-07-04 19:07
![2021-07-02 at 2 19 PM](https://user-images.githubusercontent.com/71732619/124320000-b66e3d80-db40-11eb-86df-827dc07be90d.png)

**Comment by willacuna** [comment] 2021-07-04 19:12
I was trying to point out that the instructions were incorrect.  I had
already found the solution and included it in that report.


Respectfully,
William Acuna

**Comment by ashnohe** [comment] 2021-11-05 19:50
Duplicate of #15

**Closed by ashnohe** 2021-11-05 19:50 UTC
