### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by TheWandereNo1** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#16] opened 2021-05-19 23:44 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#3

**In which task and step of the codelab can this issue be found?**
4 adopting good coding practices

**Describe the problem**
In android studio if i click on the triangle it doesnt have the fix button.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-05 19:42
Duplicate of #15

**Closed by ashnohe** 2021-11-05 19:42 UTC
