### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by ayushtiwari110** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#17] opened 2021-05-28 13:58 UTC
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#3

step 4 : Adopt good coding practices

in this step, there is written how to fix the hardcoded text issue. in this, the mentioned process says to click on the triangle in front of textview in component tree which opens a pop up with a fix option and some info.
but as of now I'm having latest android studio in which nothing happens by doing that. instead, I discovered that there is one more triangle near attributes tab which does the job. so I thought to update about this change which could help someone who is not able to locate that

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-05 19:43
Duplicate of #15

**Closed by ashnohe** 2021-11-05 19:43 UTC
