### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by albert2126** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#26] opened 2021-10-19 16:52 UTC
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#4

**In which task and step of the codelab can this issue be found?**
Task 5, step 4.

**Describe the problem**
The Gradle project settings are not in the root directory but in the HappyBirthday subdir. That's why in step 4 we must select this subdirectory. Otherwise, the IDE doesn't recognize this as a Gradle project.

**Steps to reproduce?**
1. Start the import of the new project as described.
2. In step 4, double-click the project folder. If you click Open, you will follow many steps with multiple questions.
3. This doesn't correspond to the task description, which says that the project must be recognized and open.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-05 20:02
Duplicate of #10 

Thank you @albert2126 for flagging this issue and for the description.

**Closed by ashnohe** 2021-11-05 20:02 UTC
